apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-likedme-front-test
 labels:
    app: app-likedme-front-test
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app-likedme-front-test
  template:
    metadata:
      labels:
        app: app-likedme-front-test
    spec:
      containers:
        - name: app-likedme-front-test
          image: <CUSTOM_IMAGE_TAG>
          ports:
            - containerPort: 3000
              name: http
      imagePullSecrets: 
        - name: registry-gitlab-lamoda-grp-ti
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-likedme-front-test
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-likedme-front-test
              topologyKey: kubernetes.io/hostname 
            weight: 99
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-likedme-front-test
spec:
  type: ClusterIP
  selector:
    app: app-likedme-front-test
  ports:
    - name: http
      protocol: TCP
      port: 30010
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: in-app-likedme-front-test
spec:
  ingressClassName: nginx
  rules:
    - host: app-likedme-front-test.k8s01.local
      http:
        paths:
          - backend:
              service:
                name: svc-app-likedme-front-test
                port:
                  number: 30010
            path: /
            pathType: Prefix
  tls:
   - hosts:
     - app-likedme-front-test.k8s01.local
     secretName: app-likedme-front-test-cert