FROM node:18-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_PORT=3000

COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm install react-scripts -g

COPY . ./

CMD ["npm", "start"]